schweikert/fping

src/fping.c

This reduces the CPU usage of fping somewhat (measured using top).  It helps with many fpings competing for a CPU, and/or small (1ms tested) ping intervals.

Remove heap manipulation from fast path.

---

src/fping.c

This fixes the segfault reported in issue #85

Pass ICMP unreachable message string to print_warning instead of int.

---

ci/test-06-options-f-h.pl
src/fping.c

fping has previously been strict about network address and broadcast
addreses. In the commit this is loosened a bit to permit fping to ping
cidrs with prefix length 31, which are commonly used for link ranges
(for newer equipment) and length 32 which denotes a single ip address.
For prefix lengths 31 and 32 fping will simply ignore network address
and broadcast addresses, and consider all addresses in range as a
target.

Ignore network and broadcast for cidrs /31 and /32

---

configure.ac

warning: compiling 'fping.c' with per-target flags requires 'AM_PROG_CC_C_O' in 'configure.ac'

Issue compliling on RHEL/Centos 7

---

src/fping.c

This option is very useful for checking MTU blackholes. Since fping is good at checking multiple servers @ once, together its good in a cloud hosting environment where you have a lot of hosts that need to reach each other at slightly larger than standard ethernet sizes (e.g. to handle vxlan overhead), and sometimes one server is misconfigured or one switch port.

add path mtu discovert (MTU) AKA Don't Fragment support

---

.travis.yml
ci/test-02-help.pl
src/fping.c

Hi David,
I really enjoy using fping. It is a great tool. I often have to do network convergence tests. When not using a professional traffic generator, the easiest option is to send many ping packets (e.g. 1 ping every 100ms) and measure how many ping packets were lost during the failure. Therefore, I added a new option (-o) that calculates how much outage you have observed based on the number of lost packets and the inter-packet interval. 
I tested this new option along side the traditional testing tool (home made perl script) and we observed the same results. I really hope this feature can become a part of the mainline fping program.
Thanks for all your work,
Jan

added changes for accumulated outage time

---

src/fping.c

Hi,
I am the founder of firehol.org and https://github.com/firehol/netdata (http://my-netdata.io).
This PR adds the option `-N` to `fping` to allow it output statistics in a netdata friendly format.
**For each host** given, netdata will create 3 charts, like that:
A wrapper script (`/usr/libexec/netdata/plugins.d/fping.plugin`) is required only for passing the valid options to fping. It is shown below and I'll add it to the netdata repo:
``` sh
#!/usr/bin/env bash
me="${0}"
update_every="${1-1}"
NETDATA_CONFIG_DIR="${NETDATA_CONFIG_DIR-/etc/netdata}"
fping="$(which fping || command -v fping)"
hosts=""
ping_every="$((update_every * 1000 / 2))"
retries=1
if [ ! -f "${NETDATA_CONFIG_DIR}/fping.conf" ]
then
echo >&2 "${me}: configuration file '${NETDATA_CONFIG_DIR}/fping.conf' not found - …
```

added option -N to allow fping output statistics in the format expected by netdata

---

ci/test-15-netdata.pl
src/fping.c

1. converted netdata charts to `area` charts
I think charts like this:
are nicer, than this:
2. added netdata to `trace_flag` output
3. fixed compiler warning about `setuid()` return value being ignored, by calling `perror()` on `setuid()` errors.
4. fix 100% cpu consumption introduced with https://github.com/schweikert/fping/commit/7c7e007502a3a2bd435a9e6b797387dbea8b992c

minor netdata improvements

---

src/fping.c
src/socket4.c

David,
These two commits are both trivial and hopefully appropriately explained in the commit messages.
Tested on Solaris 10 Update 8, Solaris 10 Update 11 and Solaris 11.2 with locally built gcc 4.8.5 and gcc 4.9.3 for both 32-bit and 64-bit compiles. I only have access to X86 Solaris Systems (not SPARC).
Regards,
Peter

Portability Fixes discovered on Solaris 10, but should be generally applicable

---

src/fping.c

0 is a valid file descriptor. Use -1 instead to signal a timeout. Fixes #125.

Return -1 when socket_can_read times out.

---

configure.ac

Source: https://svnweb.freebsd.org/ports/head/net/fping/files/patch-configure.ac?revision=473606&view=markup
Fix build fping with ipv6 support on FreeBSD

Fix FreeBSD ipv6 build

---

src/fping.c

Otheriwse build breaks with:
fping.c:690:24: error: ‘socket6’ undeclared (first use in this function);
did you mean ‘socket4’?

Fix build with --disable-ipv6

---

src/fping.c

Adding a sym-link for `fping6` is not quite enough to satisfy old scripts, `-6` must also be implied.

Add backward compatibility for fping6 sym-link

---

ci/test-10-option-u-x.pl
doc/fping.pod
src/fping.c

Adding -x option which allows user to specify a threshold and check if atleast those many hosts are active

---

doc/fping.pod

The option --src is an alias for the uppercase -S.
Stumbled upon this in the man page.
When running "fping -h", the option is printed correctly:
$ -s, --stats        print final stats

Corrected long option name of -s to --stats

---

src/fping.c

Proper fix is for user to abandon fping6 but at least this makes it work.
See #147 for discussion and more details.

Do not fail if using fping6 with -6 flag

---

src/fping.c

When IPv6 is disabled, hints_ai_family is set to AF_INET at initialization, resulting in the error "can't specify both -4 and -6" if the -4 option is supplied. If there's no IPv6, make the -4 option a no-op.

Fix -4 option when IPv6 disabled

---

azure-pipelines.yml

Add Azure Pipline as small alternative to travis.
Ping is not allowed in the free hosts provided by Microsoft. That's why test 14 was disabled in yaml.

Create Azure Pipline Testbuild without test-14-ping-internet-hosts.pl

---

src/fping.c

Increase some buffer sizes to eliminate format warnings.  Fixes #165

increase some buffer sizes to eliminate format warnings

---

src/fping.h

Use extern in header files when declaring global variables.  Fixes #166

use extern in header files when declaring global variables

---

ci/test-11-nopriv.pl
src/fping.c
src/fping.h
src/socket4.c
src/socket6.c

Right now if you try to use unprivileged ping (i.e. via `SOCK_DGRAM`) on the "develop" branch, it doesn't see the response packets.
There are a few problems this PR fixes:
- The "ident" value cannot be specified by unprivileged processes, so we have to get it from the kernel via `getsockname`. This change is necessary in order for it to see the ident fields line up and accept the responses.
- When using `SOCK_DGRAM` for IPv4 unprivileged ping on Linux, there is no `struct ip` at the beginning of the message read by `recvmsg`. So we have to handle that situation specially. First, we need to account for the size of the missing header when logging the responses (since it *is* data sent/received over the wire, but it's not visible to the userspace process). Second, we need to avoid treating …

Linux unprivileged ping support

---

src/fping.c

On Mac OS, the `getaddrinfo` behavior differs from Linux. If you do something silly like request address info for `AF_INET6` with an IPv4 address, it succeeds. Because of this, something like `fping -6 127.0.0.1` fails at `sendmsg` time instead of address resolution time. There's a special hint flag that you can set on Mac OS to make `getaddrinfo` behave like it would on Linux (and thus, pass the test suite).

macos: use AI_UNUSABLE hint for getaddrinfo()

---

src/fping.c

There was a difference in stats for received/transmitted packets when the Netdata protocol was used.
```
BEGIN fping.google_com_packets
SET xmt = 5
SET rcv = 5
END
BEGIN fping.google_com_quality
SET returned = 100
END
BEGIN fping.google_com_latency
SET min = 2793
SET avg = 2798
SET max = 2801
END
BEGIN fping.google_com_packets
SET xmt = 5
SET rcv = 4
END
BEGIN fping.google_com_quality
SET returned = 100
END
BEGIN fping.google_com_latency
SET min = 2781
SET avg = 2787
SET max = 2794
END
...
BEGIN fping.google_com_packets
SET xmt = 5
SET rcv = 4
END
BEGIN fping.google_com_quality
SET returned = 100
END
BEGIN fping.google_com_latency
SET min = 2789
SET avg = 2794
SET max = 2800
END
BEGIN fping.google_com_packets
SET xmt = 4
SET rcv = 4
END
BEGIN fping.google_com_quality
SET returned = 100 …
```

Fix xmt stats in Netdata output

---

ci/test-07-options-i-m.pl
doc/fping.pod
src/fping.c

ping supports printing out an intermediate summary of results and resuming via `SIGQUIT` (`ctrl-\`). fping currently prints out summary statistics only for hosts responding.  This allows a summary to be output of all hosts without terminating the run.
Sample output:
```
fping -g 192.168.42.210 192.168.42.212 -l
192.168.42.211 : [0], 84 bytes, 1.00 ms (1.00 avg, 0% loss)
192.168.42.211 : [1], 84 bytes, 2.40 ms (1.70 avg, 0% loss)
192.168.42.211 : [2], 84 bytes, 0.93 ms (1.44 avg, 0% loss)
192.168.42.211 : [3], 84 bytes, 1.31 ms (1.41 avg, 0% loss)
ICMP Host Unreachable from 192.168.42.150 for ICMP Echo sent to 192.168.42.212
ICMP Host Unreachable from 192.168.42.150 for ICMP Echo sent to 192.168.42.212
ICMP Host Unreachable from 192.168.42.150 for ICMP Echo sent to 192.168.42.212
ICMP Host …
```

Add SIGQUIT summary support similar to ping

---

src/fping.c

Moved code block for num_alive increment. Should only increase num_alive if response is not a duplicate.  
In cases where multiple pings are sent, num_alive can increase past one for a host if a duplicate ping response is received while h->num_recv ==1.

Only increase num_alive if response is not a duplicate

---

ci/test-05-options-c-e.pl
ci/test-15-netdata.pl
configure.ac
src/fping.c
src/seqmap.c
src/seqmap.h

A few fixes:
- The `-z` debug flag was implemented but not accepted by getopt_long. I added it.
- The `-z` debug flag only accepted a decimal argument, and since the argument is a bitfield, I made it possible to take a hex argument, i.e. `0xffff` enables all debug bits.
And the most important part:
- Use 1us resolution for latency measurements. This fixes #101.

Move to 1us resolution for latency measurements

---

CHANGELOG.md
ci/test-02-help.pl
ci/test-10-option-u-x.pl
src/fping.c
src/fping.h
src/seqmap.c

fixes long standing issue #113 (and original problem described in #97 and #105)

refactored event loop, now for each ping create both next-ping+timeout events

---

src/fping.c

bind to source only when option was set.
this allows to work in jails and lxc with custom IPs.
this allows IPv4 only and IPv6 only hosts

- fix regression introduced in fping 4.3

---

src/fping.c

On Linux, one needs privileges to setsockopt(SO_BINDTODEVICE), and the
current code would drop setuid root privileges too soon.
Temporarily drop privileges instead, and raise them back to issue the
privileged setsockopt().  Once we know we won't need to do any further
privileged setsockopt(), permanently drop privileges.
For now, assume SO_BINDTODEVICE is the only setsockopt that needs this.

fping: retain privileges until after privileged setsockopt

---

src/fping.c

There is a small typo in src/fping.c.
Should read `permanently` rather than `permanetly`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, permanetly -> permanently

---

src/fping.c

Commit 509f5a59cb717edf3b4ef7fe0fbf6d31f0ed0199 is related but just skipped the check when IPv6 is disabled. This fixes the check for the  `-4` option is the same way that commit 6fd4f8bd91abc43f80078bdd0084cb6d2b1de7f1 did for the `-6` option.

Allow -4 option to be given multiple times when IPv6 is enabled.

---

src/fping.c

On diffrent architecture int64_t is long int or long long int. This change use the format string macro PRId64 from inttypes.h in the print_netdata function to set individually "ld" or "lld" at printf output
Fixes #219

use formatstring macro PRId64 in print_netdata for output int64_t

---

src/fping.c

Wrong timestamp on Free- and OpenBSD and macOS fixed by disabling #define CLOCKID CLOCK_MONOTONIC
**Issues**
#203
#216

Fixed wrong timestamp under Free- and OpenBSD and macOS

---

doc/fping.pod
src/fping.c

Two small improvements to the documentation, i.e., `fping.pod` and `fping -h` output:
1. Adjust documentation for `-d` and `-n` to the implemented behavior.
2. Slightly expand the documentation for `-Q`.

Documentation improvements

---

src/fping.c

Remove dublicate include time.h entry in src/fping.c line 63.
The time.h is also included in line 48

Remove dublicate include time.h entry in fping.c

---

autoclean.sh

At least on my system (Ubuntu GNU/Linux 18.04.6 LTS), autoclean.sh
misses three files: compile, doc/Makefile, and src/Makefile.  Add
them.

add missing files to autoclean.sh

---

src/fping.c

If the compiler correctly identifies the use of HAVE_SO_TIMESTAMPNS but in runtime SO_TIMESTAMPNS cannot be used, then SO_TIMESTAMP is tried to be used as fallback. Only if this also does not work, an error message is issued for both SO_TIMESTAMPNS and SO_TIMESTAMP.
Fixed Issues #272 and #273

Fallback to SO_TIMESTAMP if SO_TIMESTAMPNS is not available

---

src/fping.c

For NetBSD this was implemented in PullRequest [225](https://github.com/schweikert/fping/pull/255)
This can also be found in the OpenBSD patch https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/ports/net/fping/patches/patch-src_fping_c?rev=1.12&content-type=text/plain

OpenBSD is not affected by the "broken alpha headers" bug, too.

---

src/seqmap.c

Fixes the following build warning under ARMv6 CPU
Version: fping-5.1
CPU: ARMv6
```
seqmap.c: In function ‘seqmap_add’:
seqmap.c:84:96: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long int’ [-Wformat=]
ing error: not enough sequence numbers available! (expire_timeout=%ld, host_nr=%d, ping_count=%d, seqmap_next_id=%d)\n",
~~^
%lld
```

Fixing build warning long int on seqmap.c line 84

---

ci/test-10-option-u-x.pl
doc/fping.pod
src/fping.c

Here is the test case for pull request #220 and issue #171 with complete copied code from the pull request.
I hope this is enough to take over the function and complete both pull requests and the issue.

Test case for "fping: add option to exit immediately once N hosts have been found" with copied code

---

src/fping.c

Initializing the structure assuming glibc layout results in
compile errors on musl, therefore do partial intialization and then
assigning the members individually.
Signed-off-by: Khem Raj <raj.khem@gmail.com>

fping: Initialize msghdr struct in a portable way

---

doc/fping.pod

'--file' has been allowed for non-root since 3.10 (see commit 86f0b1e38098ad4b7e735ee7ef10cda071d43bdc ).
This is to update the documentation since it does not reflect this change, which can be confusing.

Updating doc regarding root requirements for file parameter

---

doc/fping.pod

`http://my-netdata.io/` technically works, but it redirects to `https://netdata.cloud/`. I think it is better to update the website link.

Update Netdata website link

---

src/fping.c

This fix is part of netdata/netdata#12641

Remove `host` from Netdata chart titles

---

ci/test-15-netdata.pl

The erroneous test 15 was corrected, which did not work anymore with commit a6c3145 (remove host from netdata chart titles)

Repair the faulty test 15

---

configure.ac

Corrects the two warnings AC_GNU_SOURCE and AC_PROG_CC_STDC is obsolete when using autconf version >= 2.62 or 2.70
Issue: #284

Checking obsolete macro AC_GNU_SOURCE (autoconf-2.62) and AC_PROG_CC_STDC (autoconf-2.70) 

---

.github/workflows/test.yml

I have changed the runner no longer present in github action from ubuntu-18-04 to ubuntu-22.04

Fix deprected github action ubuntu-18.04 to ubuntu-22.04

---

configure.ac
src/fping.c

- The operating system identification has moved from incode to autoconf.
- The first step is to control CLOCK_REALTIME.
- The next step could be the identification of system under WSL, which is currently not yet required.

Autoconf os detection

---

README.md
ci/prepare-linux.sh
ci/test-07-options-i-m.pl
contrib/fping.spec
doc/fping.pod
src/fping.c

This is based on [tomangert](https://github.com/tomangert)'s original outdated pull request.
--fwmark can be used in conjunction with `ip rule` and `ip route` to route ping packets based on the mark set by the aforementioned flag.
This has been supported by Linux since kernel version [2.6.25](https://man7.org/linux/man-pages/man7/socket.7.html)
Let me know if you'd like any changes.

Add --fwmark option for Linux

---

ci/test-05-options-c-e.pl
ci/test-06-options-f-h.pl
ci/test-08-options-n-q.pl

Commits one through four add tests for existing functionality that I added in my (now closed) pull requests for new functionality. Commit five adds two tests for examples given in the man page.

Add additional tests

---

doc/fping.pod

With the options -x and -X, fping does not require all hosts to be reachable for an exit status of 0.
This addresses a comment in issue #99 suggesting such a man page update.

Update exit status description in man page

---

src/fping.c

In the function print_per_system_stats(), if packets have been lost, the number of sent packets is checked to be positive before dividing by it.  If no packets have been lost, this is not checked. Either the existing check is not needed, or both code paths need the check.
The function print_per_system_splits() is quite similar to print_per_system_stats(), and has the equivalent guards against a division by zero in both code paths, not just one of them.
In the spirit of defensive coding, I think it is better to be safe and add the missing guard against a division by zero.

Defensive coding: guard against a division by zero

---

ci/test-01-basics.pl
ci/test-03-forbidden.pl
ci/test-06-options-f-h.pl
ci/test-07-options-i-m.pl
ci/test-12-option-type.pl

This pull request is based on looking at the coverage report, and adding tests that should exercise more code paths. This should increase code coverage by tests.
This also contains pinging a local IPv6 multicast address. I do not know if this works with the GitHub CI. It does work on my GNU/Linux system at home, and IPv6 requires multicast support, so it should work.
If not all tests work with the GitHub CI, I'll close the pull request and look into the problems.

More tests

---

ci/test-05-options-c-e.pl
doc/fping.pod
src/fping.c

1. Adjust fping -h output to emphasize that -i MSEC does not change the output format.
2. Ensure that neither -a nor -u affect -c N resp. -C N operation, and test this.
3. Document in the man page that -c N and -C N override -a or -u.
This addresses issue #295. It should also help at least somewhat with issues #271 and #274.

Options "-c N" / "-C N" versus "-a" and "-u" (v2)

---

src/fping.c
src/socket6.c

* some typo fixes regarding ICMP for IPv6 sockets
* use the already existing function `stats_reset_interval()`

Two code maintenance commits

---

src/fping.c

As agreed in https://github.com/schweikert/fping/pull/298#issuecomment-1953720800

improve help output for options -c and -C

---

src/fping.c

This aligns crash_and_burn() with errno_crash_and_burn() and addresses issue #300.

always output error message in crash_and_burn()

---

src/seqmap.c

This pull request is a reduced version of @cagney and also fixes error #290 .
With this solution, however, the CPU time is faster than with pull request #306, which also fixes the error

Check if the variable next_value->ping_ts != 0 in seqmap_add()
